export enum SUCCESS_RESPONSES {
    OK = 200,
    CREATED = 201
}

export enum FAILED_RESPONSES {
    BAD = 400,
    NOT_FOUND = 404
}

export enum AUTHENTICATION_RESPONSES {
    NOT_AUTHORIZED = 403
}

export enum SERVER_RESPONSES {
    INTERNAL_ERROR = 500
}